### ISSUE TITLE
automate deploy to npm via gh-actions

### ISSUE THREAD

**Issue by KyleMit** [VermontDepartmentOfHealth/sql-cli#2]
### Learning GH Actions

* [Building Custom GitHub Actions](https://app.pluralsight.com/library/courses/building-custom-github-actions/table-of-contents)
* [Getting Started with GitHub Actions](https://app.pluralsight.com/library/courses/github-actions-getting-started/table-of-contents)

### Example

[Automatically Publish to npm using GitHub Actions](https://sergiodxa.com/articles/github-actions-npm-publish/)

```yml
name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
```
